const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Element{constructor(){this.value='1';this.max=30;this.style={};this.children=[];this.queries=new Map();this.contentWindow={postMessage:(message)=>this.messages.push(message)};this.messages=[];this.parentElement={appendChild(){}};this.options=[]}set innerHTML(v){this.html=v}get innerHTML(){return this.html}append(...v){this.children.push(...v)}replaceChildren(){this.children=[]}remove(){this.removed=true}querySelector(q){if(!this.queries.has(q))this.queries.set(q,new Element());return this.queries.get(q)}querySelectorAll(){return this.children.flatMap(l=>l.children.filter(c=>c instanceof Element))}}
const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)};const requests=[],listeners=[];let id=0;
let clock=0;const context={performance:{now:()=>clock},setInterval(){},$,document:{querySelector:()=>new Element(),createElement:()=>new Element(),createTextNode:v=>v},window:{addEventListener:(type,fn)=>listeners.push(fn)},esc:String,range:()=>({channel:0,start:'2026-10-02T12:00:00',end:'2026-10-02T12:00:30'}),stamp:d=>d.toISOString().slice(0,19),lengthLabel:String,notice(){},refresh:async()=>{},clearPlayer(){},busy:false,previewActive:false,api:async(path,data)=>{requests.push({path,data});return path==='/api/preview'?{id:'id'+(++id),url:'http://127.0.0.1:1986/stream.html?src=fixture'}:{}},console};
vm.createContext(context);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../web/multi.js'),'utf8'),context);
(async()=>{
 await vm.runInContext(`(async()=>{syncEnabled=false;renderCameraSelection([{id:0,name:'Front'},{id:4,name:'Back'}]);selectedCameras.add(4);$('camera').options=[{value:'0',textContent:'Front'},{value:'4',textContent:'Back'}];await $('view').onclick();if(multiTiles.size!==2)throw Error('Two tiles missing');$('pause-all').onclick();if(![...multiTiles.values()].every(t=>t.paused))throw Error('Shared pause failed');const first=multiTiles.get(0),second=multiTiles.get(4),old=second.id;await openTile(first,12,true);if(second.id!==old||first.segmentOffset!==12||!first.frame.src.includes('paused=1'))throw Error('Independent seek failed');first.node.querySelector('.tile-audio').onclick();if(first.muted||!second.muted)throw Error('Audio isolation failed');$('multi-seek').value=20;await $('multi-seek').onchange();if(![...multiTiles.values()].every(t=>t.segmentOffset===20))throw Error('Shared seek failed');await $('export').onclick();await first.node.querySelector('.tile-close').onclick();if(multiTiles.size!==1||multiTiles.get(4)!==second)throw Error('Independent close failed');await stopMulti();if(multiTiles.size)throw Error('Cleanup failed');})()`,context);
 assert.equal(requests.filter(r=>r.path==='/api/export').length,2);console.log('PASS: camera selection, two tiles, shared pause/seek, independent seek/close, audio isolation, batch exports, cleanup');
})().catch(e=>{console.error(e);process.exitCode=1});
